//
//  PushReceiver.h
//  MySampleApp
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//


#import <Foundation/Foundation.h>
#import "AWSPushReceiverDelegate.h"

@interface PushReceiver : NSObject<AWSPushReceiverDelegate>

@end
