//
//  UserIdentityViewController.h
//  MySampleApp
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//

#import <UIKit/UIKit.h>

@interface UserIdentityViewController : UIViewController

@property(nonatomic, weak) IBOutlet UIImageView* userImageView;
@property(nonatomic, weak) IBOutlet UILabel* userName;
@property(nonatomic, weak) IBOutlet UILabel* userID;

@end
