//
// AWSConfiguration.h
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//

#import <AWSCore/AWSCore.h>
#import <AWSCognito/AWSCognito.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:d02e4f36-cd2e-4e04-b3ae-cdcfe27b551d"
// AMAZON MOBILE ANALYTICS
#define AMAZON_MOBILE_ANALYTICS_APP_ID @"64b58bf9fd474a39a8846d06402bef78"
// PUSH
#define AWS_SNS_PLATFORM_APPLICATION_ARN @"arn:aws:sns:us-east-1:202699945646:app/APNS_SANDBOX/tasinmockapp_MOBILEHUB_1617988617"
#define AWS_SNS_ALL_DEVICE_TOPIC_ARN @"arn:aws:sns:us-east-1:202699945646:tasinmockapp_alldevices_MOBILEHUB_1617988617"
// USER FILES
#define AWS_USER_FILE_MANAGER_S3_BUCKET_NAME @"tasinmockapp-userfiles-mobilehub-1617988617"
