//
//  UserDataStorageViewController.h
//  MySampleApp
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//

#import <UIKit/UIKit.h>

@interface UserDataStorageViewController : UIViewController

@property (weak, nonatomic) IBOutlet UITextView *featureTextView;

- (IBAction)demoUserFileStorage:(UIButton *)sender;

- (IBAction)demoUserSettings:(UIButton *)sender;

@end
