//
//  AWSPushReceiverDelegate.h
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//

#ifndef AWSPushReceiverDelegate_h
#define AWSPushReceiverDelegate_h

/**
 A delegate for receiving push notifications.
 */
@protocol AWSPushReceiverDelegate <NSObject>

@required

/**
 Indicates the device received a Push Notifiation.
 
 @param userInfo    A dictionary that contains information related to the remote notification, potentially including a badge number for the app icon, an alert sound, an alert message to display to the user, a notification identifier, and custom data. The provider originates it as a JSON-defined dictionary that iOS converts to an `NSDictionary` object; the dictionary may contain only property-list objects plus `NSNull`.
 */
- (void)didReceivePushNotification:(NSDictionary *)userInfo;

@end

#endif /* AWSPushReceiverDelegate_h */
